### ISSUE TITLE
Formatting 

### ISSUE THREAD

**Issue by molmedo3** [richmass1/markdown-parser#3]
https://github.com/richmass1/markdown-parser/blob/68bd915c50720fd1830cae9f85fa5acf6a47f2fa/MarkdownParse.java#L33

This if-else statement can possibly be formatted look nicer and cleaner.

So, the code can be formatted like the following: 

```
...
}
else
{
   ...
}
```

**Comment by richmass1** [comment]
I respectfully disagree.
https://www.oracle.com/java/technologies/javase/codeconventions-statements.html
Oracle, the company that maintains Java, formats if-else the same way I do.
